GroupQuestion = [
			["Khó khăn lớn nhất của đất nước ta sau cách mạng tháng Tám gì?", "Các kẻ thù ngoại xâm, nội phản", "Nạn đói, nạn dốt đe doạ nghiêm trọng cuộc sống của nhân dân ta.", "Ngân quỹ nhà nước trống rỗng.", "Các tổ chức phản cách mạng ra sức chống phá cách mạng."],
			["Quân đội Đồng minh các nước vào nước ta sau năm 1945 là", "quân Anh, quân Mĩ", "quân Pháp, quân Anh", "Quân Anh, quân Trung Hoa Dân quốc", "quân Pháp, quân Trung Hoa Dân quốc"],
			["Sau cách mạng tháng 8 năm 1945, chúng ta phải đối mặt với nhiều kẻ thù, trong đó nguy hiểm nhất là", "quân Trung Hoa Dân Quốc.", "thực dân Pháp.", "đế quốc Anh.", "phát xít Nhật."],
			["Quân Trung Hoa Dân quốc và tay sai của chúng ở miền Bắc có âm mưu gì?", "Cướp chính quyền của ta.", "Giải giáp khí giới quân Nhật.", "Giúp đỡ chính quyền cách mạng nước ta.", "Đánh quân Anh."],
			["Khó khăn nghiêm trọng nhất của nước Việt Nam Dân chủ Cộng hòa sau Cách mạng tháng Tám năm 1945 là", "giặc ngoại xâm.", "nạn đói.", "giặc dốt.", "tài chính."],
			["Tình hình tài chính nước ta sau thắng lợi của cách mạng tháng Tám như thế nào?", "Ngân sách Nhà nước trống rỗng.", "Tài chính bước đầu được xây dựng.", "Tài chính phát triển", "Tài chính lệ thuộc vào Nhật – Pháp."],
			["Nguyên nhân cơ bản nhất dẫn đến phong trào “ Đồng khởi “ 1959 – 1960 là gì ?", "Có nghị quyết Hội nghị lần thứ XV của Đảng về đường lối CM miền Nam", "Mỹ - Diệm phá hoại Hiệp định Giơnevơ, thực hiện chính sách “ tố cộng “, “diệt cộng“.", "M ỹ Diệm phá hoại hiệp định, thực hiện chiến dịch tố cộng diệt cộng, thi hành luật 10-59  lê máy chém đi khắp miền Nam làm cho cách mạng miền Nam bị tổn thất nặng nề", "Do chính sách cai trị của Mỹ - Diệm làm cho CM miền Nam bị tổn thất nặng."],
			["Cuộc đấu tranh chính trị tiêu biểu nhất của nhân dân miến Nam năm 1963 là ?", "Cuộc biểu tình của 2 vạn tăng ni phật tử Huế ( 08- 5- 1963).", "Hòa thượng Thích Quảng Đức tự thiêu để phản đốI chính quyền Diệm ở Sài Gòn.", "Cuộc biểu tình của 70 vạn quần chúng ở Sài Gòn ( 16- 6- 1963)..", "Cuộc đảo chính lật đỗ Ngô Đình Diệm."],
			["Ngày 01- 11- 1963 là ngày gì ?", "Ngô Đình Diệm bị lật đổ", "Kế hoạch Johnson Mac Namara được thông qua.", "Johnson lên nắm chính quyền.", "Tổng thống Kennơdi bị ám sát."],
			["Cuộc hành quân mang tên “ánh sáng sao “ nhằm thí điểm cho chiến lược chiến tranh nào của Mỹ ?", "Chiến tranh đơn phương.", "Chiến tranh đặc biệt.", "Chiến tranh cục bộ..", ". Việt Nam hóa chiến tranh."],
			["Chiến thắng Vạn Tường ( 18- 8- 1968 ) đã chứng tỏ điều gì?", "Lực lượng vũ trang CM miền Nam đủ sức đương đầu và đánh bại quân viễn chinh Mỹ", "Lực lượng vũ trang miền Nam đã trưởng thành.", "Quân viễn chinh Mỹ đã mất khả năng chiến đấu.", "CM miền Nam đã giành thắng lợi trong việc đánh bại “ chiến tranh cục bộ “ của Mỹ"],
			["Cuộc phản công chiến lược mùa khô 1965 - 1966 của Mỹ kéo dài trong bao lâu, với bao nhiêu cuộc hành quân lớn nhỏ?", "4 tháng với 450 cuộc hành quân..", "4 tháng với 540 cuộc hành quân.", "6 tháng với 450 cuộc hành quân.", "7 tháng với 540 cuộc hành quân."],
			["Cuộc hành quân lớn nhất của Mỹ trong cuộc phản công chiến lược mùa khô 1966- 1967 vào Đông nam bộ là cuộc hành quân nào?", "Gian Xơnxity.", "Atơnbôrơ.", "Xêđanphôn", "Cuộc hành quân ánh sáng sao."],
			["Ý nghiã lớn nhất của cuộc tổng công kích, tổng nổi dậy tết Mậu Thân 1968 là gì?", "Làm lung lai ý chí xâm lược của quân viễn chinh Mỹ, buộc Mỹ phải tuyên bố ” phi Mỹ hóa ” chiến tranh xâm lược.", "Mỹ phải đến Hội nghị Pari để đàm phán với ta", "Giáng một đòn nặng vào quân Mỹ, làm cho chúng không dám đưa quân Mỹ và chư hầu vào miền Nam.", "Buộc Mỹ phải chấm dứt không điều kiện chiến tranh phá họai miền Bắc."],
			["Điểm khác nhau giữa chiến tranh đặc biệt và “Việt nam hóa chiến tranh” là gì ?", "Có sự phối hợp đáng kể cuả lực lượng chiến đấu Mỹ", "Dưới sự chỉ huy cuả hệ thống cố vấn quân sự Mỹ.", "Sử dụng lực lượng chủ yếu là quân nguỵ.", "Hình thức chiến tranh thực dân mới của Mỹ."],
			
		];